services:
  - type: web
    name: frontend-bigjohn
    buildCommand: cd frontend/bigjohn && npm install && npm run build
    staticPublish: true
    publishPath: frontend/bigjohn/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
