services:
  - type: web
    name: frontend-bigjohn
    buildCommand: npm install && npm run build
    staticPublish: true
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
